### ISSUE TITLE
Rangliste: Hintergrundfarbe überall gleich (gebrochenes Weiss)

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#12]
Aktuell ist die Hintergrundfarbe hinter der Rangliste anders als hinter dem Parallel Coordinates Plot: 

![image](https://user-images.githubusercontent.com/7261044/40479668-80d39b3e-5f4c-11e8-9d5c-1ef84f6d38c6.png)

**Comment by FUUbi** [comment]
see 60819f5
