### ISSUE TITLE
Rangliste: Abstand zwischen Plot und Scrollbar vergrössern, so dass nichts abgeschnitten wird

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#16]
Aktuell wird "0%" über dem Scrollbar angezeigt, und die Markers auf der Grundlinie unten werden abgeschnitten: 

![image](https://user-images.githubusercontent.com/7261044/40480176-f43abe9e-5f4d-11e8-844a-e466f2cd04ea.png)

**Comment by FUUbi** [comment]
Commit 60819f5
