### ISSUE TITLE
Fehlende Indikatorenbezeichner im Datenexport hinzufügen

### ISSUE THREAD

**Issue by FUUbi** [statabs-test/quartierindex#23]
![image](https://user-images.githubusercontent.com/12157082/46571318-28ef6600-c973-11e8-9662-658be253d222.png)
Im Schritt zwei wird rechts neben den Button "Positiv & Negativ" ein zusätzlicher Beschreibungstext benötigt, dieser fehlt im Datenexport .

**Comment by jb3-2** [comment]
@JE1982 Haben wir diese Texte schon irgendwo? @FUUbi Aus welchem Bild hast du diesen Screenshot, ich finde dies nirgends.

**Comment by jb3-2** [comment]
@FUUbi Habe die Texte in einem separaten tsv File hochgeladen, siehe https://github.com/statabs-test/quartierindex/blob/master/data/indikatoren_texte.tsv

**Comment by FUUbi** [comment]
Der Screenshot stammt vom Screendesign pdf, welches im Slack resources channel gepostet wurde.
