### ISSUE TITLE
Berechnungsergebnis aus

### ISSUE THREAD

**Issue by FUUbi** [statabs-test/quartierindex#35]
unterhalb der Rangliste

**Comment by daugsbi** [comment]
1. Textänderung zu "mit Gewicht X"
2. Bei Umbruch auf gleiche Höhe wie Text nach Auflistungszeichen

**Comment by jb3-2** [comment]
Sieht gut aus, danke. Ganz am Ende steht noch eine geschlossene Klammer, die sollte wohl weg.

**Comment by bhzunami** [comment]
Ja das sollte nicht sein, wurde entfernt.
