### ISSUE TITLE
Anzeige des Disclaimers

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#40]
Der Disclaimer soll auf der Startseite unter den Navigationsbuttons beim Seitenaufruf angezeigt werden. Zudem soll der Besucher die Möglichkeit haben, ihn auszublenden. 

Disclaimer Inhalt: 
> Die von Ihnen vorgenommenen Einstellungen (Auswahl, Bewertung und Gewichtung) werden nicht gespeichert. 
> Sie werden ausschliesslich für die Berechnung der Rangliste genutzt.

Der Disclaimer soll auch nochmals auf der letzten Seite (Rangliste) angezeigt werden.

**Comment by JE1982** [comment]
Den Vorschlag, den Disclaimer solange anzuzeigen, bis er weggeklickt wurde, finde ich gut. Bitte so umsetzen.
