### ISSUE TITLE
Anpassung der Indikatoren

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#45]
Folgende Indikatoren erhalten einen neuen Namen:

- Anteil Konfessionslose, statt Anteil Personen ohne Religionszugehörigkeit
- Sesshaftigkeit, statt Anteil Sesshafte

**Comment by bhzunami** [comment]
Sollen hier auch noch die Texte für Bewertung geändert werden.
> Ein hohe Sesshaftigkeit ist für mich

**Comment by jb3-2** [comment]
@bhzunami Ja, gerne!
