### ISSUE TITLE
Verbesserte Navigation

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#53]
Keine Zeilenumbrüche in den Buttons (Weiter zur Gewichtung).
Tippfehler korrigieren bei 'Zurück zu**r** Bewertung'
Zurück-Buttons sollten auf der linken Seite sein.
Weiter-Buttons sollten auf der rechten Seite sein.

**Comment by bhzunami** [comment]
Hier stellt es sich die Frage ob das nur auf der 3. Seite (Indikatorengewichtung) sein soll oder für alle Seiten gilt.
Ich würde ein einheitliches Konzept begrüssen, da es sonst für den Benutzer unübersichtlich wird, wenn der 'Zurück zu...' einmal rechts und danach links steht. 

Mein Vorschlag:
- Alle Weiter-Buttons werden immer rechts dargestellt
- Alle Zurück-Buttons werden immer links dargestellt
- 'Rangliste erstellen' wird immer rechts unter allen anderen Buttons dargestellt.

Die Frage ist, ob der Rangliste erstellen Buttons wirklich auf jeder Seite dargestellt werden muss? Was ist hier der Mehrwert.

**Comment by daugsbi** [comment]
Wurde entsprechend Vorlage angepasst. Den oben genannten Vorschlag würde ich jedoch besser finden begrüssen. Die Navigation von Schritt 3 zu 2 ist inkonsistent.  (Rangliste Button immer am gleichen Ort, Links zurück, rechts weiter oder Rangliste) ist jedoch aktuell nach Vorlage umgesetzt. @jb3-2
