### ISSUE TITLE
Fehlender Kantonswert

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#58]
Der Kantonswert sollte auch in der Rangliste angezeigt werden.
Der Balken wird schwarz dargestellt und hat keine Rankingnummer. 

Die Daten für den Kanton sind zur Zeit noch nicht verfügbar. Deshalb wird der arithmetischer Mittelwert von allen Indikatoren verwendet.

**Comment by bhzunami** [comment]
Bitte noch die richtigen Werte nachliefern.

**Comment by daugsbi** [comment]
Es wurde jeweils der Mittelwert zu gleichen Teilen pro Quartiere genommen. Behalte den Issue noch offen, bis die korrekten Daten vorhanden sind.

**Comment by jb3-2** [comment]
Habe schon fast alle Werte, warte nur noch auf die Sozialhilfequote BS.

**Comment by jb3-2** [comment]
Fehlende Kantonswerte sind nun hinzugefügt im File https://github.com/statabs-test/quartierindex/blob/develop/data/quartierindex_2018.csv
