### ISSUE TITLE
Navigationsbuttons bei Ranking anpassen

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#62]
Die Buttons bei der Rangliste sollten auf die ganze Breite verteilt werden. 
Zusätzlich muss der Text angepasst werden.

- Auswahl ändern
- Bewertung ändern
- Gewichtung ändern

**Comment by daugsbi** [comment]
Der Text muss noch angepasst werden.
Die Grösse soll sich an der Breite der Indikatoren orientieren
