### ISSUE TITLE
Veränderungen im Balkendiagramm nachvollziehbarer machen

### ISSUE THREAD

**Issue by bhzunami** [statabs-test/quartierindex#64]
Veränderungen auf der X-Achse in den Balkendiagrammen werden durch eine Transition nachvollziehbar dargestellt.
Hat eine Änderung aber Einfluss auf die Ranking Reihenfolge (Y-Achse) ist das zu wenig ersichtlich. Für den Benutzer sieht es aus, als ob eine Veränderung eines Indikator andere Indikatoren beeinflusst, was aber nicht der Fall ist. Die Verschiebung der Y-Achse sollte auch durch eine Transition dargestellt werden.

**Comment by daugsbi** [comment]
Die Transition wurde für die Rangliste (Label und Balken) implementiert. Auf die Transition pro Indikator wurde aus Performance Gründen verzichtet (insbesondere bei der Auswahl vieler Indikatoren störend). Die Veränderung der Rangliste ist nun nachvollziehbar.

**Comment by jb3-2** [comment]
Sieht gut aus, danke!
