### ISSUE TITLE
Sicherheitslücken patchen

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#65]
Hier ein Auszug aus https://snyk.io/: 

![grafik](https://user-images.githubusercontent.com/7261044/49866474-2a705b00-fe08-11e8-8005-05202fe79bcf.png)

**Comment by jb3-2** [comment]
Siehe auch den SNYK auto-generierten Pull Request: https://github.com/statabs-test/quartierindex/pull/37

**Comment by bhzunami** [comment]
Die Sicherheitslücken beziehen sich auf den Master. Im develop Branch sollten diese nicht mehr vorhanden sein.

**Comment by jb3-2** [comment]
Sicherheitslücken sind nun gepatcht, siehe Screenshot bzw. https://app.snyk.io/org/jb3-2/project/1aee0416-5d7f-4089-9008-83e1cac23e44 

![image](https://user-images.githubusercontent.com/7261044/52039419-c5e29a00-2534-11e9-8894-04937b45e596.png)
