### ISSUE TITLE
Tooltip auf Balken

### ISSUE THREAD

**Issue by daugsbi** [statabs-test/quartierindex#68]
Wir erhalten einen Vorschlag, wie die Tooltips aussehen sollten inkl. Inhalt. Die Grundidee ist bei der Rangliste den gerechneten Wert anzuzeigen. Bei den Indikatoren den Ursprungswert inkl. Einheit. 
Blockiert durch #67.

**Comment by daugsbi** [comment]
Der Tooltip soll auch aufrufbar sein, falls der Wert 0 ist. Evt. kleiner Balken anzeigen

**Comment by FUUbi** [comment]
Für die Umsetzung benötigen wir noch ein Mockup (Inhalt, Design).

**Comment by jb3-2** [comment]
@FUUbi Das neue Screendesign inkl. den verschiedenen Tooltips habe ich gier hochgeladen: https://github.com/statabs-test/quartierindex/blob/develop/data/Screendesign-Quartier-Index-Tooltip.pdf

Die EInheit kommt wie besprochen in die neue Spalte wert_txt, werde ich noch heute hochladen.

**Comment by jb3-2** [comment]
@FUUbi Herzlichen Dank, das funktioniert schon mal sehr gut. Ein paar kleine Dinge als Feedback von @JE1982 und @grilli73 noch: 

- [ ] Der Whitespace um den Text in den Tooltips ist zu knapp, bitte da noch einen breiteren Rand einfügen. Dazu am besten auch gleich den Tooltip vergrössern, oder die Grösse dynamisch machen (falls das geht in eurer Tooltip Lib). 
![image](https://user-images.githubusercontent.com/7261044/52729266-248a2800-2fb9-11e9-92de-8dde5494fbbc.png)

- [ ] Kannst du im Tooltip der Rangliste (gelb) auch noch das Wohnviertel schreiben? Der Tooltip überdeckt nämlich manchmal den zugehörigen Wohnviertel-Namen.
![image](https://user-images.githubusercontent.com/7261044/52729668-e5a8a200-2fb9-11e9-8ea7-ba90dc225a2d.png)

- [ ] Bei "Erwerbstätigenquote 2012-2016" wird nach dem - umgebrochen. Könntest du den Strich z.B. ersetzen durch ein no break dash (https://stackoverflow.com/a/7691604), so dass vor oder nach "2012-2016" umgebrochen wird (oder sonst eine technische Umsetzung, die für dich passt)?
Bei diesem Indikator ist auch der Tooltip zu klein, so dass Text ausserhalb des Tooltips geschrieben wird.
![image](https://user-images.githubusercontent.com/7261044/52729583-bb56e480-2fb9-11e9-8eb6-2a9d0f43c070.png)

**Comment by bhzunami** [comment]
Habe die Tooltips angepasst.

**Comment by jb3-2** [comment]
Herzlichen Dank! Wie gerade mit @FUUbi am Telefon besprochen:
- Habe das superscript-2 noch ersetzt durch das entsprechende Unicode Zeichen in den Daten im Master Branch, bitte neu builden und deployen
- Bitte den Pipe | im Tooltip ersetzen durch ein Komma: [Wert], Rang [Rang]
- Bitte noch ein klein Wenig mehr Margin schaffen im Tooltip, so dass der Text nie an oder über den Rand des Tooltips reicht. 
![image](https://user-images.githubusercontent.com/7261044/53079229-45d99f80-34f6-11e9-8b9c-d366505f556e.png)

**Comment by jb3-2** [comment]
In der Rangliste ist der Tooltip von „Anteil Personen in Einpersonenhaushalten“ noch nicht gut in Firefox, der Text ragt über das Kästchen hinaus.

**Comment by bhzunami** [comment]
Sieht es aus wie im oberen Screenshot? Denn beim mir im Firefox sieht es gut aus.

![image](https://user-images.githubusercontent.com/3340922/53793128-82ad8980-3f2d-11e9-9ac4-c33aa47ae392.png)

Firefox: 65.0.1
OS: Mac 10.14.3

**Comment by jb3-2** [comment]
Auf Mac ist es wie in Deinem Screenshot schön, auf Windows mit Firefox  6.5.2ESR hingegen nicht ganz: 

![884c5fe9-ff34-4362-b357-924c68134820](https://user-images.githubusercontent.com/7261044/53820417-06866680-3f6c-11e9-99b1-7393acf30759.jpeg)

**Comment by jb3-2** [comment]
Wir würden gerne morgen 8.3.2019 den Quartierindex live setzen. Klappt das, den Fehler noch zu beheben bis dann? Er besteht noch im gh-pages Branch. Meiner Erfahrung nach ist Arial in Firefox für Windows ein Bisschen breiter oder so, eine Verbreiterung des Tooltips um ein paar Pixelchen könnte dieses Problem evtl. lösen.

**Comment by bhzunami** [comment]
Also bei mir im Firefox unter Windows habe ich das Problem nicht mehr gesehen?

**Comment by jb3-2** [comment]
Bei mir gerade jetzt schon, siehe Screenshot...

![image](https://user-images.githubusercontent.com/7261044/53958616-ca751200-40e1-11e9-8939-2a46cfcce6e7.png)

**Comment by bhzunami** [comment]
Kann es sein, dass die Seite noch im Speicher ist bei dir im Firefox? Bitte schaue dir die Seite mal im incognito modus an.

So sieht es bei mir unter Windows 10, Firefox version 65.0.2 aus:
![photo5767101911646974465](https://user-images.githubusercontent.com/3340922/53959103-0492e380-40e3-11e9-88b2-f21655641745.jpg)

**Comment by FUUbi** [comment]
Bei mir tritt der Fehler auf Windows, Firefox auch auf. Hab das div mal um 5px vergrössert, konnte es aber nicht validieren, da ich in der Windows VM keine Entwicklungsumgebung habe...

**Comment by jb3-2** [comment]
Auch im Incognito-Modus kommt bei mir der Tootlipp Überlauf.

**Comment by jb3-2** [comment]
Herzlichen Dank, ist nun gefixt!
