### ISSUE TITLE
Beschriftung in Gewichtung

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#7]
Texte in Gewichtung sollen wie folgt sein:

Mit der Gewichtung wird festgelegt, wie stark ein Indikator in die Index-Berechnung einfliesst. Folgende Gewichte sind wählbar:

sehr unwichtig: 0.25, eher unwichtig: 0.5, eher wichtig: 0.75, sehr wichtig: 1.0

Der Anteil Sozialhilfeempfänger ist für mich
Der Anteil Ausländer ist für mich
Der Anteil Personen ohne Religionszugehörigkeit ist für mich
Der Anteil Personen in Einpersonenhaushalten ist für mich
Die Gymnasialquote ist für mich
Der Altersquotient ist für mich
Der Anteil Sesshafte ist für mich
Der Jugendquotient ist für mich
Das Baujahr der Wohngebäude ist für mich
Der Anteil Einfamilienhäuser ist für mich
Der Anteil Grünfläche ist für mich
Die Fläche pro Wohnung ist für mich
Die Wohnfäche pro Kopf ist für mich
Die Vermögenssteuer ist für mich
Die Einkommenssteuer ist für mich
Die Erwerbstätigenquote ist für mich
Der Anteil Arbeitsplätze pro Kopf ist für mich
Die Arbeitslosenquote ist für mich

Statt: 
![image](https://user-images.githubusercontent.com/7261044/40478555-aa3cbd3c-5f49-11e8-8a3c-b7dea5291534.png)

**Comment by daugsbi** [comment]
Die einzelnen Texte, welche sich auf die Indikatoren beziehen im Schritt Gewichtung und Bewertung, siehe ebenfalls #6, sollten in diesem Fall manuell festgelegt werden. Eine einfache und flexible Lösung wären zwei Spalten im Spiderranks.csv export mit dem jeweiligen Hilfetext für Gewichtung und Bewertung.

**Comment by jb3-2** [comment]
Schon fast perfekt. Die dynamischen Texte sind umgesetzt, der statische Text sollte auch angepasst werden, genau wie oben beschrieben.

**Comment by daugsbi** [comment]
Sorry, der statische Text ist mir entgangen. Danke für die Überprüfung. 
Die Abstände sind nun ebenfalls grösser

**Comment by jb3-2** [comment]
Super, das ist nun umgesetzt.
