### ISSUE TITLE
Dynamische Skalierung der X-Achse

### ISSUE THREAD

**Issue by daugsbi** [statabs-test/quartierindex#70]
Die X-Achse soll dynamisch auf Grund der Daten skaliert werden, ohne Fixierung auf -1 bis 1. Das Cartesian Grid inkl. des weglassens der mittleren Beschriftung soll beibehalten werden.

**Comment by jb3-2** [comment]
Bitte hier (wie heute mit @FUUbi besprochen) die X-Achsen Labels als Vielfache von von 0.25 * 10<sup>-n</sup> oder 0.1 * 10<sup>-n</sup> schreiben, anstatt wie aktuell einfach als Vielfache von (max-min)/4. 

Im Beispiel unten also -0.25, 0, 0.25, 0.5. 

![image](https://user-images.githubusercontent.com/7261044/51110740-e9e67180-17f9-11e9-9484-0e89db05d8a6.png)
