### ISSUE TITLE
Firefox: Unterschiedliche Höhe von Indikator löschen(X) und Auswahlliste

### ISSUE THREAD

**Issue by daugsbi** [statabs-test/quartierindex#76]
Der Container mit dem X zum schliessen erscheint kleiner als die Auswahlliste daneben

**Comment by FUUbi** [comment]
Dies scheint ein Firefox Bug zu sein, der Rand der HTML Elemente "div" und "select" wächst in unterschiedliche Richtungen.  
![image](https://user-images.githubusercontent.com/12157082/50995784-62121600-1520-11e9-841e-97653f3c418f.png)

**Comment by bhzunami** [comment]
Ich habe das Problem mit Firefox 64.0 (64Bit) nicht.
<img width="241" alt="image" src="https://user-images.githubusercontent.com/3340922/51036076-5409d700-15ac-11e9-9937-2bd69cab8479.png">

**Comment by bhzunami** [comment]
Mhh auch wenn ich es vergrösserte konnte ich dieses Verhalten nicht wirklich feststellen.
Dafür sehen die Änderungen im Chrome jetzt so aus.
![image](https://user-images.githubusercontent.com/3340922/51072451-2a5eb780-1661-11e9-9446-36a6f9ecc90d.png)

Weiss nicht ob das besser ist. Besprich es doch mit Jonas. Ich denke wenn es beim hinein zoomen verschiebt, kann man das weglassen. Denn eigentlich vergrössert man die Seite ja nicht.

**Comment by FUUbi** [comment]
Gut, demnach passen sich die Browser den Präferenzen der Betriebssysteme an. Der erste Fehler betrifft daher Firefox auf Windows und der zweite Fehler Chrome auf macOS. 
Ich habe den Rand des Select Elements auf none gesetzt, auf Windows schaut es für alle Browser (IE11, Firefox & Chrome) ok aus. 
Wie schaut es nun auf macOS aus?

**Comment by bhzunami** [comment]
Perfekt! 
![image](https://user-images.githubusercontent.com/3340922/51072937-d60c0580-1669-11e9-879c-5e1b85a100dd.png)

**Comment by jb3-2** [comment]
Super in Firefox!
