### ISSUE TITLE
Klammer in Text der Rangliste

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#78]
In der Rangliste steht ganz links unten noch eine Klamer. Bitte diese entfernen, siehe Screenshot: 
![image](https://user-images.githubusercontent.com/7261044/51892291-c0087f80-23a1-11e9-93f0-3b888fbb8bcb.png)

**Comment by bhzunami** [comment]
Duplicate of #35. Webseite wurde noch nicht neu erstellt. Im Code sollte die ')' gelöscht sein.

**Comment by jb3-2** [comment]
Ist nun weg, danke.
