### ISSUE TITLE
Komma statt Punkt als Dezimaltrennzeichen

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#82]
Bitte an den Orten, die in den Screenshots gezeigt werden, Komma als Dezimaltrennzeichen verwenden statt Punkt. 

- [x] Hier im Text bei allen Zahlen:
![image](https://user-images.githubusercontent.com/7261044/53736285-8e477480-3e89-11e9-9337-b443c25db892.png)

- [x] Hier im Tooltip und in den X-Achsen Beschriftungen:
![image](https://user-images.githubusercontent.com/7261044/53736399-e67e7680-3e89-11e9-8dcc-b33453285afc.png)

**Comment by bhzunami** [comment]
Müssen die Labels auf der X-Achse auch ein ',' haben oder können diese den '.' behalten?

**Comment by jb3-2** [comment]
Ja gerne, die Labels auf der X-Achse sollen auch ein , statt ein . als Dezimaltrennzeichen haben.
