### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jb3-2** [statabs-test/quartierindex#84]
In meinem Datenfile hatte es noch einen Tippfehler: "Wohnfäche". Dies habe ich nun im develop Branch geflickt (siehe https://github.com/statabs-test/quartierindex/commit/b551bed892d2b78b5c9704cb587a52041aded390). 

Kann bitte jemand neu builden und deployen, damit dieser Fehler in der App geflickt ist? Danke!

![image](https://user-images.githubusercontent.com/7261044/54291149-71f3b800-45ac-11e9-8c35-b649d01608fe.png)

![image](https://user-images.githubusercontent.com/7261044/54291181-7d46e380-45ac-11e9-9b3a-bb608f18801f.png)

![image](https://user-images.githubusercontent.com/7261044/54291207-889a0f00-45ac-11e9-8dc4-450d12fb60c0.png)

![image](https://user-images.githubusercontent.com/7261044/54291248-951e6780-45ac-11e9-9c1c-3638a819d93c.png)

**Comment by bhzunami** [comment]
Neuste Version ist online.
